---
- name: Get the latest version of gog
  ansible.builtin.uri:
    url: https://api.github.com/repos/andornaut/gog/releases/latest
    return_content: true
  register: gog_version

- name: Set architecture variable for x86_64
  ansible.builtin.set_fact:
    gog_arch: "x86_64"
  when: ansible_facts.architecture == "x86_64"

- name: Set architecture variable for aarch64
  ansible.builtin.set_fact:
    gog_arch: "arm64"
  when: ansible_facts.architecture == "aarch64"

- name: Install gog
  ansible.builtin.unarchive:
    src: "https://github.com/andornaut/gog/releases/download/{{ gog_version.json.tag_name }}/gog_{{ ansible_facts.system | lower }}_{{ gog_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    include: ["gog"]
    mode: "0755"
  become: true
