---
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - acpi
    - apt-transport-https
    - atool
    - atop
    - autotools-dev
    - bash
    - bison
    - build-essential
    - ca-certificates
    - cifs-utils
    - cmake
    - coreutils
    - curl
    - debconf-utils
    - dnsutils
    - elinks
    - exfat-fuse
    - exfat-utils
    - exuberant-ctags
    - fakeroot
    - fonts-font-awesome
    - fonts-inconsolata
    - fonts-roboto
    - gcc
    - git
    - highlight
    - htop
    - i2c-tools
    - iftop
    - iotop
    - iperf
    - irssi
    - libc6
    - libfontconfig
    - libfreetype6
    - libfreetype6-dev
    - linux-firmware
    - lm-sensors
    - make
    - mercurial
    - mutt
    - nethogs
    - nmap
    - ntpdate
    - openconnect
    - openresolv
    - openvpn
    - perl
    - powertop
    - ranger
    - rsync
    - rxvt-unicode-256color
    - screen
    - smartmontools
    - smbclient
    - software-properties-common
    - sox
    - ssh
    - sysstat
    - tmux
    - tree
    - unzip
    - vim
    - wget
    - whois
    - zip
  become: true

- name: Enable multiverse repositories
  command: add-apt-repository {{ item }}
  with_items:
    - multiverse
    - universe
  become: true

- name: set timezone
  timezone:
    name: "{{ base_timezone }}"
  become: true

- name: Re-map capslock key to escape key
  command: localectl set-x11-keymap "" "" "" caps:escape
  ignore_errors: yes
  become: true

- name: Install cache-command
  get_url:
    url: https://raw.githubusercontent.com/andornaut/cache-command/master/cache-command
    dest: /usr/local/bin/
    mode: 0755
  become: true

- name: Check for the latest version of gog
  uri:
    url: https://api.github.com/repos/andornaut/gog/releases/latest
    return_content: "yes"
  register: gog_version

- name: Install gog
  get_url:
    url: https://github.com/andornaut/gog/releases/download/{{ gog_version.json.tag_name }}/gog-linux-amd64
    dest: /usr/local/bin/
    mode: 0755
  become: true

- import_tasks: storage-space-alert.yml
