--- 
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - acpi
    - apt-transport-https
    - atool
    - atop
    - autotools-dev
    - bash
    - build-essential
    - ca-certificates
    - cifs-utils
    - cmake
    - coreutils
    - cups
    - curl
    - debconf-utils
    - dnsutils
    - elinks
    - exuberant-ctags
    - fakeroot
    - fonts-font-awesome
    - fonts-inconsolata
    - fonts-roboto
    - gcc
    - git
    - highlight
    - htop
    - i2c-tools
    - iftop
    - iotop
    - iperf
    - irssi
    - libc6
    - libfontconfig
    - libfreetype6
    - libfreetype6-dev
    - linux-firmware
    - lm-sensors
    - make
    - mercurial
    - mpv
    - mutt
    - ncftp
    - nethogs
    - nmap
    - ntpdate
    - openconnect
    - openvpn
    - perl
    - powertop
    - python-software-properties
    - ranger
    - rsync
    - samba
    - screen
    - smartmontools
    - smbclient
    - "{% if ansible_distribution_release == 'xenial' %}software-center{% else %}gnome-software{% endif %}"
    - software-properties-common
    - sox
    - ssh
    - sysstat
    - tmux
    - tree
    - ubuntu-drivers-common
    - ubuntu-restricted-extras
    - unzip
    - vim
    - wget
    - whois
    - zip
  become: true

- name: Enable multiverse repositories
  command: add-apt-repository multiverse
  become: true

- name: set timezone
  timezone:
    name: "{{ timezone }}"
  become: true

- name: Install storage-space-alert
  get_url:
    url: https://raw.githubusercontent.com/andornaut/storage-space-alert/master/storage-space-alert
    dest: /usr/local/bin/storage-space-alert
    mode: 0755
  become: true

- include: mscorefonts.yml
- include: source-code-pro.yml
