---
- name: Install system packages
  apt:
    name:
      - acpi
      - atool
      - atop
      - autoconf
      - autotools-dev
      - bash
      - build-essential
      - ca-certificates
      - cifs-utils
      - cmake
      - coreutils
      - curl
      - dnsutils
      - elinks
      - exfat-fuse
      - exfat-utils
      - exuberant-ctags
      - fakeroot
      - fonts-font-awesome
      - fonts-inconsolata
      - fonts-roboto
      - gcc
      - git
      - highlight
      - htop
      - i2c-tools
      - iftop
      - iotop
      - iperf
      - irssi
      - libc6
      - libfontconfig
      - libfreetype6
      - libfreetype6-dev
      - linux-firmware
      - lm-sensors
      - make
      - mercurial
      - mutt
      - nethogs
      - net-tools
      - nmap
      - ntpdate
      - openconnect
      - openresolv
      - openvpn
      - perl
      - powertop
      - ranger
      - rsync
      - rxvt-unicode-256color
      - screen
      - smartmontools
      - smbclient
      - software-properties-common
      - sox
      - ssh
      - sysstat
      - tmux
      - tree
      - unrar
      - unzip
      - vim
      - wget
      - whois
      - zip
    state: latest
    update_cache: yes
  become: true

- name: Enable multiverse repositories
  command: add-apt-repository {{ item }}
  with_items:
    - multiverse
    - universe
  become: true

- name: Set timezone
  timezone:
    name: "{{ base_timezone }}"
  become: true

- name: Re-map capslock key to escape key
  command: localectl set-x11-keymap "" "" "" caps:escape
  ignore_errors: yes
  become: true

- name: Install cache-command
  get_url:
    url: https://raw.githubusercontent.com/andornaut/cache-command/master/cache-command
    dest: /usr/local/bin/
    mode: 0755
  become: true

- import_tasks: gog.yml

- import_tasks: mrs.yml

- import_tasks: storage-space-alert.yml
