---
- name: Download and extract soure-code-pro package
  unarchive:
    src: 'https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip'
    dest: /tmp
    remote_src: yes
    creates: /tmp/source-code-pro-2.030R-ro-1.050R-it

- name: Copy source-code-pro TTF files
  copy:
    src: /tmp/source-code-pro-2.030R-ro-1.050R-it/TTF/
    dest: /usr/share/fonts/truetype/source-code-pro
  register: source_code_pro_files
  become: true

- name: Update font cache
  command: fc-cache
  when: source_code_pro_files.changed
  become: true

