---
- name: Install storage-space-alert
  get_url:
    url: https://raw.githubusercontent.com/andornaut/storage-space-alert/master/storage-space-alert
    dest: /usr/local/bin/
    mode: 0755
  become: true

- name: Periodically run storage-space-alert
  cron:
    name: storage-space-alert
    cron_file: /etc/crontab
    user: root
    minute: "30"
    job: storage-space-alert
  become: true
