---
- name: Reload systemd
  systemd_service:
    daemon_reload: yes
  become: true

- name: Update font cache
  command: fc-cache
  become: true

- name: Apply keyboard changes
  command: udevadm trigger --subsystem-match=input --action=change
  become: true
